#!/bin/bash

SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"

_check() {
    if [[ $? -ne 0 ]]; then
        echo "Error processing: $1"
        exit 1
    fi
}

_do_build() {
    echo "Configuring ..."
    cmake -B build
    _check "configuring"
    echo "Building ..."
    cmake --build build -j4
    _check "build"
}

_clean() {
    cd ${SCRIPT_DIR} || _check "cd to root"
    rm -rf \
        build \
        external \

    cd - || _check "cd back"
}

if [[ "$#" = "0" ]]; then
    # With no parameter: build
    _do_build
elif [[ "$1" = "clean" ]]; then
    _clean
    echo "Done."
elif [[ "$1" = "unit" ]]; then
    _do_build
    shift
    echo "Testing... "
    for unit in "${SCRIPT_DIR}"/build/test/bin/unit_*
    do
        $unit "$@"
        _check "$unit"
    done
elif [[ "$1" = "asm" ]]; then
    _do_build
    shift
    echo "Testing... "
    for asm in "${SCRIPT_DIR}"/build/test/bin/aut_*
    do
        $asm "$@"
        _check "$asm"
    done
elif [[ "$1" = "benchmark" ]]; then
    _do_build
    shift
    echo "Testing... "
    for benchmark in "${SCRIPT_DIR}"/build/test/bin/benchmark_*
    do
        $benchmark "$@"
        _check "$benchmark"
    done
elif [[ "$1" = "ctest" ]]; then
    shift
    _do_build
    cmake --build build -- test
    _check "ctest"
elif [[ "$1" = "demo" ]]; then
    _do_build
    _demo
else
    echo "Usage: `basename $0` [unit|asm|benchmark|ctest|clean]"
    echo "    unit      - build and run google unit tests"
    echo "    asm       - build and run ASM unit tests"
    echo "    benchmark - build and run google benchmark tests"
    echo "    ctest     - build and run google unit tests (from CMake)"
    echo "    clean     - clean build"
fi
